---
- name: Set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ hostname_hostname }} {{ hostname_hostname + '.' + hostname_domain if hostname_domain else '' }}"

- name: Set hostname in /etc/hostname and /etc/mailname
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "etc/hostname.j2"
      dest: "/etc/hostname"
    - src: "etc/mailname.j2"
      dest: "/etc/mailname"

- name: Set hostname with hostname command
  command: "hostname --file /etc/hostname"
  changed_when: False

# FIXME hostnamectl depends on dbus
#- name: Set hostname with systemd
#  command: "hostnamectl set-hostname {{ hostname_hostname }}{{'.' + hostname_domain if hostname_domain else '' }}"
#  when: ansible_service_mgr == 'systemd'
